// frontend/src/app/pages/home-page-new/home-page.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router,RouterModule,ActivatedRoute } from '@angular/router';
import { ApiService, CompanyInfo, Service } from '../../services/api.service';

@Component({
  selector: 'app-home-page',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.css']
})
export class HomePageComponent implements OnInit {
  // Données de l'entreprise
  companyInfo: CompanyInfo | null = null;
  isVideoPlaying = false;
private videoElement: HTMLVideoElement | null = null;


  // Section About
  aboutCommitments = [
    {
      icon: '💬',
      title: 'On vous écoute vraiment',
      description: 'On prend le temps de comprendre vos besoins réels, sans vous presser. Votre situation nous intéresse.'
    },
    {
      icon: '✅',
      title: 'On est honnête',
      description: 'Pas de fausses promesses. On vous dit clairement ce qu\'on peut faire pour vous, sans exagérer.'
    },
    {
      icon: '🤝',
      title: 'On vous accompagne',
      description: 'De la première rencontre jusqu\'à la signature, on est là pour vous guider à chaque étape.'
    }
  ];

  // Section Contact
  contactForm: FormGroup;
  isSubmitting = false;
  showSuccessMessage = false;
  contactItems = [
    { icon: '📞', title: 'Téléphone', value: '+225 05 03 97 47 75' },
    { icon: '✉️', title: 'Email', value: 'christroiagence@gmail.com' },
    { icon: '📍', title: 'Agence', value: 'Abidjan, Côte d\'Ivoire' },
    { icon: '🕒', title: 'Horaires', value: 'Lun - Ven: 8h00 - 18h00' }
  ];

  constructor(private fb: FormBuilder, private apiService: ApiService,private router: Router) {
    this.contactForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(2)]],
      lastName: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.required]],
      service: ['', [Validators.required]],
      message: ['', [Validators.required, Validators.minLength(10)]]
    });
  }

  ngOnInit() {
    // Chargement des données de l'entreprise
    this.apiService.getCompanyInfo().subscribe({
      next: (data) => {
        this.companyInfo = data;
      },
      error: (err) => {
        console.error('Erreur chargement company info:', err);
        this.companyInfo = {
          name: 'Christ-Roi Agence',
          description: 'Votre partenaire de confiance pour trouver un emploi ou un candidat à Abidjan. On travaille avec honnêteté et simplicité.',
          email: 'christroiagence@gmail.com',
          phone: '+225 05 03 97 47 75',
          location: 'Abidjan, Côte d\'Ivoire',
          hours: 'Lun - Ven: 8h00 - 18h00',
          values: ['Honnêteté', 'Accompagnement', 'Simplicité', 'Confiance'],
          stats: {
            clients: '500+',
            projects: '1000+',
            experience: '5+ ans',
            support: '24/7'
          }
        };
      }
    });
  }

  // ===== MÉTHODES HERO =====
  heroBtnHover(event: MouseEvent) {
    const button = event.currentTarget as HTMLElement;
    button.classList.add('hover');
  }

  heroBtnLeave(event: MouseEvent) {
    const button = event.currentTarget as HTMLElement;
    button.classList.remove('hover');
  }

  scrollToNext() {
    const nextSection = document.getElementById('services');
    if (nextSection) {
      nextSection.scrollIntoView({
        behavior: 'smooth',
        block: 'start'
      });
    }
  }

  // ===== MÉTHODES SERVICES =====
  servicesCardHover(event: MouseEvent) {
    const card = event.currentTarget as HTMLElement;
    card.classList.add('hover');
  }

  servicesCardLeave(event: MouseEvent) {
    const card = event.currentTarget as HTMLElement;
    card.classList.remove('hover');
  }

  navigateToCandidats() {
  // Navigue vers personnel avec l'onglet "offres" actif (candidats cherchent des offres)
  this.router.navigate(['/personnel'], { queryParams: { view: 'offres' } });
}


  navigateToRecruteurs() {
  // Navigue vers personnel avec l'onglet "candidats" actif (recruteurs cherchent des candidats)
  this.router.navigate(['/personnel'], { queryParams: { view: 'candidats' } });
}

  // ===== MÉTHODES ABOUT =====
  aboutVideoHover(event: MouseEvent) {
    const container = event.currentTarget as HTMLElement;
    container.classList.add('hover');
  }

  aboutVideoLeave(event: MouseEvent) {
    const container = event.currentTarget as HTMLElement;
    container.classList.remove('hover');
  }

  aboutCardHover(event: MouseEvent) {
    const card = event.currentTarget as HTMLElement;
    card.classList.add('hover');
  }

  aboutCardLeave(event: MouseEvent) {
    const card = event.currentTarget as HTMLElement;
    card.classList.remove('hover');
  }

  // ===== MÉTHODES CONTACT =====
  contactItemHover(event: MouseEvent) {
    const item = event.currentTarget as HTMLElement;
    item.classList.add('hover');
  }

  contactItemLeave(event: MouseEvent) {
    const item = event.currentTarget as HTMLElement;
    item.classList.remove('hover');
  }

  contactSubmitHover(event: MouseEvent) {
    const button = event.currentTarget as HTMLElement;
    if (!this.isSubmitting && !this.contactForm.invalid) {
      button.classList.add('hover');
    }
  }

  contactSubmitLeave(event: MouseEvent) {
    const button = event.currentTarget as HTMLElement;
    if (!this.isSubmitting) {
      button.classList.remove('hover');
    }
  }

  async onSubmit() {
    if (this.contactForm.invalid) {
      this.markAllFieldsAsTouched();
      return;
    }

    this.isSubmitting = true;
    this.showSuccessMessage = false;

    try {
      await this.simulateApiCall();
      this.handleSuccess();
    } catch (error: any) {
      console.error('Erreur envoi message:', error);
      this.handleError();
    }
  }

  private simulateApiCall(): Promise<void> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (Math.random() > 0.2) {
          resolve();
        } else {
          reject(new Error('Erreur de réseau simulée'));
        }
      }, 2000);
    });
  }

  private markAllFieldsAsTouched() {
    Object.keys(this.contactForm.controls).forEach(key => {
      const control = this.contactForm.get(key);
      if (control) {
        control.markAsTouched();
      }
    });
  }

  private handleSuccess() {
    this.isSubmitting = false;
    this.showSuccessMessage = true;
    this.contactForm.reset();

    setTimeout(() => {
      this.showSuccessMessage = false;
    }, 5000);
  }

  private handleError() {
    this.isSubmitting = false;
    this.openFallbackEmail(this.contactForm.value);
  }

  private openFallbackEmail(formData: any): void {
    const sujet = formData.service === 'candidat' ? 'Je cherche un emploi' : 'Je cherche un candidat';
    const subject = `Contact Christroi: ${sujet}`;
    const body = `
Prénom: ${formData.firstName || ''}
Nom: ${formData.lastName || ''}
Email: ${formData.email || ''}
Téléphone: ${formData.phone || ''}
Statut: ${formData.service === 'candidat' ? 'Je cherche un emploi' : 'Je cherche un candidat'}

Message:
${formData.message || ''}
    `.trim();

    const mailtoLink = `mailto:christroiagence@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  }

  shouldShowError(controlName: string): boolean {
    const control = this.contactForm.get(controlName);
    return control ? control.invalid && control.touched : false;
  }
  ngAfterViewInit() {
  this.setupVideoIntersectionObserver();
}

private setupVideoIntersectionObserver() {
  this.videoElement = document.querySelector('.founder-video');
  
  if (this.videoElement && 'IntersectionObserver' in window) {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting && this.videoElement) {
            // La vidéo est visible, on peut la lire
            this.videoElement.play().then(() => {
              this.isVideoPlaying = true;
            }).catch(error => {
              console.log('Lecture automatique bloquée:', error);
            });
          } else if (this.videoElement && !entry.isIntersecting) {
            // La vidéo n'est plus visible, on la met en pause
            this.videoElement.pause();
            this.isVideoPlaying = false;
          }
        });
      },
      {
        threshold: 0.5 // Déclenche quand 50% de la vidéo est visible
      }
    );

    observer.observe(this.videoElement);
  }
}

onVideoLoaded(event: Event) {
  console.log('Vidéo chargée et prête');
}

toggleVideoPlayback() {
  if (this.videoElement) {
    if (this.videoElement.paused) {
      this.videoElement.play().then(() => {
        this.isVideoPlaying = true;
      });
    } else {
      this.videoElement.pause();
      this.isVideoPlaying = false;
    }
  }
}

scrollToContact() {
  const contactSection = document.getElementById('contact');
  if (contactSection) {
    contactSection.scrollIntoView({
      behavior: 'smooth',
      block: 'start'
    });
  }
}
}
<!-- SECTION HERO -->
<section class="hero" id="hero">
  <div class="hero-background">
    <div class="hero-gradient-1"></div>
    <div class="hero-gradient-2"></div>
  </div>

  <div class="hero-content">
    <div class="hero-text-wrapper">
      <h1 class="hero-title">
        <span class="title-word">Trouvez le bon job ou le bon employé</span>
      </h1>

      <p class="hero-description">
        Chez Christ-Roi Agence, on vous aide à trouver votre place dans le monde du travail à Abidjan. 
        Des opportunités réelles, un accompagnement personnalisé.
      </p>

      <div class="hero-buttons">
        <a href="#services" class="btn btn-primary" (mouseenter)="heroBtnHover($event)" (mouseleave)="heroBtnLeave($event)">
          <span class="btn-text">Je cherche un emploi</span>
          <span class="btn-icon">→</span>
        </a>
        <a href="#services" class="btn btn-secondary" (mouseenter)="heroBtnHover($event)" (mouseleave)="heroBtnLeave($event)">
          <span class="btn-text">Je cherche un employé</span>
          <span class="btn-icon">→</span>
        </a>
      </div>
    </div>
  </div>

  <div class="scroll-indicator" (click)="scrollToNext()">
    <span class="scroll-text">Comment ça marche ?</span>
    <div class="scroll-arrow">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <polyline points="6 9 12 15 18 9"></polyline>
      </svg>
    </div>
  </div>
</section>

<!-- SECTION SERVICES -->
<section class="services-section" id="services">
  <div class="section-container">
    <div class="section-header" data-animate="fade-in">
      <h2 class="section-title">On vous aide concrètement</h2>
      <p class="section-subtitle">Que vous soyez à la recherche d'un travail ou d'un employé, nous trouvons la solution qui vous convient</p>
      <div class="title-accent"></div>
    </div>

    <div class="services-grid" data-animate="fade-in">
      <!-- Carte pour les candidats -->
      <div class="service-card" data-animate="slide-up" 
           (mouseenter)="servicesCardHover($event)"
           (mouseleave)="servicesCardLeave($event)"
           (click)="navigateToCandidats()">
        <div class="card-header">
          <div class="service-icon">👤</div>
          <div class="service-accent"></div>
        </div>
        <div class="card-content">
          <h3 class="service-title">Je cherche un emploi</h3>
          <p class="service-description">
            Chauffeur, vigile, nounou, femme de ménage , etc ... On vous aide à trouver le job qui correspond à vos besoins.
          </p>
          <div class="service-link">
            <span>Voir les offres disponibles</span>
            <span class="link-arrow">→</span>
          </div>
        </div>
      </div>

      <!-- Carte pour les recruteurs -->
      <div class="service-card" data-animate="slide-up"
           (mouseenter)="servicesCardHover($event)"
           (mouseleave)="servicesCardLeave($event)"
           (click)="navigateToRecruteurs()">
        <div class="card-header">
          <div class="service-icon">🏢</div>
          <div class="service-accent"></div>
        </div>
        <div class="card-content">
          <h3 class="service-title">Je cherche un employé</h3>
          <p class="service-description">
            Besoin d'un chauffeur de confiance, d'une nounou sérieuse ou d'un vigile compétent ? On vous présente les bonnes personnes.
          </p>
          <div class="service-link">
            <span>Trouver le bon profil</span>
            <span class="link-arrow">→</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- SECTION ABOUT -->
<section class="about-section" id="about">
  <div class="section-container">
    <div class="section-header" data-animate="fade-in">
      <h2 class="section-title">Notre façon de travailler</h2>
      <div class="title-accent"></div>
    </div>

    <div class="about-intro" data-animate="slide-up">
      <p>
        À Abidjan, on sait que trouver un bon emploi ou un bon employé n'est pas simple.
        On avance avec simplicité et sérieux, sans détour : le but, c'est que tout le monde y gagne, vraiment.
      </p>
    </div>

    <div class="about-video-section">
      <!-- Video Container -->
      <div class="video-featured-container" 
           (mouseenter)="aboutVideoHover($event)"
           (mouseleave)="aboutVideoLeave($event)">
        <div class="video-wrapper">
          <video #founderVideo 
                 class="founder-video" 
                 poster="assets/videos/poster.jpg" 
                 muted
                 (loadedmetadata)="onVideoLoaded($event)">
            <source src="assets/videos/fondatrice-explication.mp4" type="video/mp4">
            Votre navigateur ne supporte pas la vidéo.
          </video>
          <div class="video-overlay" (click)="toggleVideoPlayback()">
            <div class="play-button" *ngIf="!isVideoPlaying">
              <div class="play-icon">▶</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Scrolling Message with Arrows -->
      <div class="scrolling-message-container" (click)="scrollToContact()">
        <div class="scrolling-message">
          <div class="message-content">
            <span class="message-text">📞 Appelez-nous au +225 05 03 97 47 75</span>
            <span class="message-separator">•</span>
            <span class="message-text">✉️ Ou envoyez-nous un message directement</span>
            <span class="message-separator">•</span>
            <span class="message-text">🚀 Trouvons ensemble la solution qui vous convient</span>
            <span class="message-separator">•</span>
            <span class="message-text">💼 Des opportunités réelles pour tous</span>
          </div>
          
          <!-- Flèches intégrées au message -->
          <div class="inline-arrows">
            <div class="arrow-down"></div>
            <div class="arrow-down"></div>
            <div class="arrow-down"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- SECTION CONTACT -->
<section class="contact-section" id="contact">
  <div class="section-container">
    <div class="section-header" data-animate="fade-in">
      <h2 class="section-title">Parlons-en directement</h2>
      <p class="section-subtitle">Venez nous voir à l'agence ou envoyez-nous un message</p>
      <div class="title-accent"></div>
    </div>

    <div class="contact-wrapper">
      <!-- Informations de contact -->
      <div class="contact-info-section">
        <div class="info-header">
          <h3>On vous écoute</h3>
          <p>Une question ? Un projet ? On discute autour d'un café à notre agence.</p>
        </div>

        <div class="contact-items">
          <div class="contact-item" 
               *ngFor="let item of contactItems"
               (mouseenter)="contactItemHover($event)"
               (mouseleave)="contactItemLeave($event)">
            <div class="item-icon">{{ item.icon }}</div>
            <div class="item-content">
              <h4>{{ item.title }}</h4>
              <p>{{ item.value }}</p>
            </div>
          </div>
        </div>

        <div class="confidence-badge">
          <span class="badge-icon">💬</span>
          <p>On vous répond simplement et rapidement, sans jargon compliqué</p>
        </div>
      </div>

      <!-- Formulaire de contact -->
      <div class="contact-form-section">
        <div class="form-header">
          <h3>Envoyez-nous un message</h3>
          <p>On vous recontacte pour fixer un rendez-vous à l'agence</p>
        </div>

        <form [formGroup]="contactForm" (ngSubmit)="onSubmit()" class="contact-form">
          <div class="form-row">
            <div class="form-group">
              <label for="firstName">Prénom *</label>
              <input 
                type="text" 
                id="firstName" 
                formControlName="firstName"
                placeholder="Votre prénom"
                [class.error]="contactForm.get('firstName')?.invalid && contactForm.get('firstName')?.touched"
              >
              <div class="error-message" *ngIf="contactForm.get('firstName')?.invalid && contactForm.get('firstName')?.touched">
                Le prénom est requis
              </div>
            </div>

            <div class="form-group">
              <label for="lastName">Nom *</label>
              <input 
                type="text" 
                id="lastName" 
                formControlName="lastName"
                placeholder="Votre nom"
                [class.error]="contactForm.get('lastName')?.invalid && contactForm.get('lastName')?.touched"
              >
              <div class="error-message" *ngIf="contactForm.get('lastName')?.invalid && contactForm.get('lastName')?.touched">
                Le nom est requis
              </div>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group">
              <label for="email">Email *</label>
              <input 
                type="email" 
                id="email" 
                formControlName="email"
                placeholder="votre@email.com"
                [class.error]="contactForm.get('email')?.invalid && contactForm.get('email')?.touched"
              >
              <div class="error-message" *ngIf="contactForm.get('email')?.invalid && contactForm.get('email')?.touched">
                <span *ngIf="contactForm.get('email')?.errors?.['required']">L'email est requis</span>
                <span *ngIf="contactForm.get('email')?.errors?.['email']">Format d'email invalide</span>
              </div>
            </div>

            <div class="form-group">
              <label for="phone">Téléphone *</label>
              <input 
                type="tel" 
                id="phone" 
                formControlName="phone"
                placeholder="+225 00 00 00 00"
                [class.error]="contactForm.get('phone')?.invalid && contactForm.get('phone')?.touched"
              >
              <div class="error-message" *ngIf="contactForm.get('phone')?.invalid && contactForm.get('phone')?.touched">
                Le téléphone est requis
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="service">Vous êtes *</label>
            <select id="service" formControlName="service" required>
              <option value="">Choisissez une option</option>
              <option value="candidat">Je cherche un emploi</option>
              <option value="recruteur">Je cherche un candidat</option>
            </select>
          </div>

          <div class="form-group">
            <label for="message">Message *</label>
            <textarea 
              id="message" 
              formControlName="message" 
              rows="5"
              placeholder="Dites-nous ce que vous cherchez (métier, disponibilités, besoins...)"
              [class.error]="contactForm.get('message')?.invalid && contactForm.get('message')?.touched"
            ></textarea>
            <div class="error-message" *ngIf="contactForm.get('message')?.invalid && contactForm.get('message')?.touched">
              Le message est requis
            </div>
          </div>

          <button 
            type="submit" 
            class="submit-btn"
            [disabled]="contactForm.invalid || isSubmitting"
            [class.loading]="isSubmitting"
            (mouseenter)="contactSubmitHover($event)"
            (mouseleave)="contactSubmitLeave($event)">
            <span class="btn-text" *ngIf="!isSubmitting">Envoyer mon message</span>
            <div class="btn-loading" *ngIf="isSubmitting">
              <div class="loading-spinner"></div>
              <span>Envoi en cours...</span>
            </div>
          </button>
        </form>

        <div class="success-message" *ngIf="showSuccessMessage">
          <div class="success-icon">✓</div>
          <div class="success-content">
            <h4>Message envoyé !</h4>
            <p>On vous contacte très vite pour prendre rendez-vous.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// christ-roi-personnel/src/components/HomePage.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  ChevronDown, 
  Phone, 
  Mail, 
  MapPin, 
  Clock,
  MessageCircle,
  CheckCircle,
  Handshake,
  UserCheck,
  Loader2,
  Send,
  Star,
  Award,
  Heart
} from 'lucide-react';

const HomePage: React.FC = () => {
  const navigate = useNavigate();
  const [contactForm, setContactForm] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    service: '',
    message: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccessMessage, setShowSuccessMessage] = useState(false);

  // Données de l'entreprise
  const companyInfo = {
    name: 'Christ-Roi Agence',
    description: 'Votre partenaire de confiance pour trouver un emploi ou un candidat à Abidjan. On travaille avec honnêteté et simplicité.',
    email: 'christroiagence@gmail.com',
    phone: '+225 05 03 97 47 75',
    location: 'Abidjan, Côte d\'Ivoire',
    hours: 'Lun - Ven: 8h00 - 18h00',
    values: ['Honnêteté', 'Accompagnement', 'Simplicité', 'Confiance'],
    stats: {
      clients: '500+',
      projects: '1000+',
      experience: '5+ ans',
      support: '24/7'
    }
  };

  // Section About - engagements
  const aboutCommitments = [
    {
      icon: <MessageCircle className="w-8 h-8" />,
      title: 'On vous écoute vraiment',
      description: 'On prend le temps de comprendre vos besoins réels, sans vous presser. Votre situation nous intéresse.'
    },
    {
      icon: <CheckCircle className="w-8 h-8" />,
      title: 'On est honnête',
      description: 'Pas de fausses promesses. On vous dit clairement ce qu\'on peut faire pour vous, sans exagérer.'
    },
    {
      icon: <Handshake className="w-8 h-8" />,
      title: 'On vous accompagne',
      description: 'De la première rencontre jusqu\'à la signature, on est là pour vous guider à chaque étape.'
    }
  ];

  // Informations de contact
  const contactItems = [
    { icon: <Phone className="w-6 h-6" />, title: 'Téléphone', value: '+225 05 03 97 47 75' },
    { icon: <Mail className="w-6 h-6" />, title: 'Email', value: 'christroiagence@gmail.com' },
    { icon: <MapPin className="w-6 h-6" />, title: 'Agence', value: 'Abidjan, Côte d\'Ivoire' },
    { icon: <Clock className="w-6 h-6" />, title: 'Horaires', value: 'Lun - Ven: 8h00 - 18h00' }
  ];

  // Navigation vers les services
  const navigateToCandidats = () => {
    // Navigue vers personnel avec l'onglet "offres" actif (candidats cherchent des offres)
    navigate('/personnel?view=offres');
  };

  const navigateToRecruteurs = () => {
    // Navigue vers personnel avec l'onglet "candidats" actif (recruteurs cherchent des candidats)
    navigate('/personnel?view=candidats');
  };

  // Scroll vers section suivante
  const scrollToNext = () => {
    const nextSection = document.getElementById('services');
    if (nextSection) {
      nextSection.scrollIntoView({
        behavior: 'smooth',
        block: 'start'
      });
    }
  };

  // Scroll vers contact
  const scrollToContact = () => {
    const contactSection = document.getElementById('contact');
    if (contactSection) {
      contactSection.scrollIntoView({
        behavior: 'smooth',
        block: 'start'
      });
    }
  };

  // Gestion du formulaire
  const handleFormChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setContactForm(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Validation simple
    if (!contactForm.firstName || !contactForm.lastName || !contactForm.email || !contactForm.phone || !contactForm.service || !contactForm.message) {
      alert('Veuillez remplir tous les champs');
      return;
    }

    setIsSubmitting(true);
    setShowSuccessMessage(false);

    try {
      // Simulation d'un appel API
      await new Promise(resolve => setTimeout(resolve, 2000));
      handleSuccess();
    } catch (error) {
      console.error('Erreur envoi message:', error);
      handleError();
    }
  };

  const handleSuccess = () => {
    setIsSubmitting(false);
    setShowSuccessMessage(true);
    setContactForm({
      firstName: '',
      lastName: '',
      email: '',
      phone: '',
      service: '',
      message: ''
    });

    setTimeout(() => {
      setShowSuccessMessage(false);
    }, 5000);
  };

  const handleError = () => {
    setIsSubmitting(false);
    // Ouvrir l'email client par défaut
    const sujet = contactForm.service === 'candidat' ? 'Je cherche un emploi' : 'Je cherche un candidat';
    const subject = `Contact Christroi: ${sujet}`;
    const body = `
Prénom: ${contactForm.firstName || ''}
Nom: ${contactForm.lastName || ''}
Email: ${contactForm.email || ''}
Téléphone: ${contactForm.phone || ''}
Statut: ${contactForm.service === 'candidat' ? 'Je cherche un emploi' : 'Je cherche un candidat'}

Message:
${contactForm.message || ''}
    `.trim();

    const mailtoLink = `mailto:christroiagence@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  };

  return (
    <div className="home-page min-h-screen textured-bg">
      {/* SECTION HERO LUXURY */}
      <section className="hero relative h-screen flex items-center justify-center overflow-hidden">
        {/* Image de fond décorative */}
        <img
          src="/images/premium_photo-1661611453390-0e5a2e299fac.avif"
          alt="Professionnels au travail"
          className="hero-image"
        />
        
        {/* Overlay gradient royal */}
        <div className="absolute inset-0 bg-gradient-hero"></div>
        
        <div className="hero-content">
          <div className="animate-fade-in-up">
            <h1 className="hero-title">
              Trouvez le bon job ou le bon employé
            </h1>
          </div>

          <div className="animate-fade-in-up animate-delay-200">
            <p className="hero-subtitle">
              Chez Christ-Roi Agence, nous vous aidons à trouver votre place dans le monde du travail à Abidjan. 
              Des opportunités réelles, un accompagnement personnalisé.
            </p>
          </div>

          <div className="flex flex-col md:flex-row gap-6 justify-center animate-fade-in-up animate-delay-300">
            <button
              onClick={navigateToCandidats}
              className="btn-primary flex items-center justify-center gap-3 text-lg"
            >
              <UserCheck className="w-5 h-5" />
              <span>Je cherche un emploi</span>
              <ChevronDown className="w-4 h-4" />
            </button>
            <button
              onClick={navigateToRecruteurs}
              className="btn-secondary flex items-center justify-center gap-3 text-lg"
            >
              <Handshake className="w-5 h-5" />
              <span>Je cherche un employé</span>
              <ChevronDown className="w-4 h-4" />
            </button>
          </div>
        </div>

        <button 
          onClick={scrollToNext}
          className="absolute bottom-8 left-1/2 transform -translate-x-1/2 text-white hover:text-secondary transition-colors cursor-pointer animate-bounce-slow"
        >
          <div className="text-center">
            <div className="text-sm mb-2">Comment ça marche ?</div>
            <ChevronDown className="w-6 h-6 mx-auto" />
          </div>
        </button>
      </section>

      {/* SECTION SERVICES LUXURY */}
      <section id="services" className="section bg-gradient-base">
        <div className="luxury-container">
          <div className="section-header animate-fade-in-up">
            <h2 className="section-title">
              On vous aide concrètement
            </h2>
            <p className="section-subtitle">
              Que vous soyez à la recherche d'un travail ou d'un employé, nous trouvons la solution qui vous convient
            </p>
            <div className="section-divider"></div>
          </div>

          <div className="grid-2 max-w-4xl mx-auto">
            {/* Carte pour les candidats */}
            <div 
              onClick={navigateToCandidats}
              className="card-premium hover-lift cursor-pointer group animate-fade-in-left"
            >
              <div className="p-8">
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-16 h-16 bg-primary-100 rounded-full flex items-center justify-center group-hover:bg-primary-200 transition-colors">
                    <UserCheck className="w-8 h-8 text-primary" />
                  </div>
                  <div className="w-8 h-1 bg-gradient-royal"></div>
                </div>
                
                <h3 className="text-2xl font-display font-semibold text-gray-900 mb-4">
                  Je cherche un emploi
                </h3>
                <p className="text-gray-600 mb-6 leading-relaxed">
                  Chauffeur, vigile, nounou, femme de ménage, etc... On vous aide à trouver le job qui correspond à vos besoins.
                </p>
                
                <div className="flex items-center gap-2 text-primary font-semibold group-hover:text-primary-600 transition-colors">
                  <span>Voir les offres disponibles</span>
                  <ChevronDown className="w-4 h-4" />
                </div>
              </div>
            </div>

            {/* Carte pour les recruteurs */}
            <div 
              onClick={navigateToRecruteurs}
              className="card-premium hover-lift cursor-pointer group animate-fade-in-right"
            >
              <div className="p-8">
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-16 h-16 bg-secondary-100 rounded-full flex items-center justify-center group-hover:bg-secondary-200 transition-colors">
                    <Handshake className="w-8 h-8 text-secondary" />
                  </div>
                  <div className="w-8 h-1 bg-gradient-royal"></div>
                </div>
                
                <h3 className="text-2xl font-display font-semibold text-gray-900 mb-4">
                  Je cherche un employé
                </h3>
                <p className="text-gray-600 mb-6 leading-relaxed">
                  Besoin d'un chauffeur de confiance, d'une nounou sérieuse ou d'un vigile compétent ? On vous présente les bonnes personnes.
                </p>
                
                <div className="flex items-center gap-2 text-secondary font-semibold group-hover:text-secondary-600 transition-colors">
                  <span>Trouver le bon profil</span>
                  <ChevronDown className="w-4 h-4" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION ABOUT LUXURY */}
      <section id="about" className="section bg-white">
        <div className="luxury-container">
          <div className="section-header animate-fade-in-up">
            <h2 className="section-title">
              Nos engagements
            </h2>
            <p className="section-subtitle">
              Voici ce qui nous définit et ce qui fait notre différence
            </p>
            <div className="section-divider"></div>
          </div>

          <div className="grid-3 max-w-6xl mx-auto">
            {aboutCommitments.map((commitment, index) => (
              <div 
                key={index}
                className="text-center p-8 rounded-2xl hover:shadow-xl transition-all duration-300 group hover-lift animate-fade-in-up"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="w-20 h-20 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-6 group-hover:bg-primary-200 transition-colors">
                  <div className="text-primary">
                    {commitment.icon}
                  </div>
                </div>
                
                <h3 className="text-xl font-display font-semibold text-gray-900 mb-4">
                  {commitment.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {commitment.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION CONTACT LUXURY */}
      <section id="contact" className="section bg-gradient-base">
        <div className="luxury-container">
          <div className="section-header animate-fade-in-up">
            <h2 className="section-title">
              Contactez-nous
            </h2>
            <p className="section-subtitle">
              Une question ? Besoin d'aide ? On est là pour vous accompagner
            </p>
            <div className="section-divider"></div>
          </div>

          <div className="grid-2 max-w-6xl mx-auto">
            {/* Formulaire de contact luxury */}
            <div className="card-premium animate-fade-in-left">
              <div className="p-8">
                <h3 className="text-2xl font-display font-semibold text-gray-900 mb-6 flex items-center gap-3">
                  <Heart className="w-6 h-6 text-primary" />
                  Envoyez-nous un message
                </h3>
                
                {showSuccessMessage && (
                  <div className="success-state mb-6">
                    <CheckCircle className="w-5 h-5" />
                    <span>Votre message a été envoyé avec succès !</span>
                  </div>
                )}

                <form onSubmit={handleSubmit} className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">Prénom</label>
                      <input
                        type="text"
                        name="firstName"
                        value={contactForm.firstName}
                        onChange={handleFormChange}
                        required
                        className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                        placeholder="Votre prénom"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">Nom</label>
                      <input
                        type="text"
                        name="lastName"
                        value={contactForm.lastName}
                        onChange={handleFormChange}
                        required
                        className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                        placeholder="Votre nom"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">Email</label>
                      <input
                        type="email"
                        name="email"
                        value={contactForm.email}
                        onChange={handleFormChange}
                        required
                        className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                        placeholder="votre@email.com"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">Téléphone</label>
                      <input
                        type="tel"
                        name="phone"
                        value={contactForm.phone}
                        onChange={handleFormChange}
                        required
                        className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                        placeholder="+225 XX XX XX XX"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Vous êtes</label>
                    <select
                      name="service"
                      value={contactForm.service}
                      onChange={handleFormChange}
                      required
                      className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                    >
                      <option value="">Sélectionnez votre situation</option>
                      <option value="candidat">Je cherche un emploi</option>
                      <option value="recruteur">Je cherche un employé</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Message</label>
                    <textarea
                      name="message"
                      value={contactForm.message}
                      onChange={handleFormChange}
                      required
                      rows={6}
                      className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent transition-all resize-none"
                      placeholder="Décrivez votre besoin en quelques mots..."
                    ></textarea>
                  </div>

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full btn-primary flex items-center justify-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isSubmitting ? (
                      <>
                        <Loader2 className="w-5 h-5 animate-spin" />
                        <span>Envoi en cours...</span>
                      </>
                    ) : (
                      <>
                        <Send className="w-5 h-5" />
                        <span>Envoyer le message</span>
                      </>
                    )}
                  </button>
                </form>
              </div>
            </div>

            {/* Informations de contact luxury */}
            <div className="space-y-8 animate-fade-in-right">
              <div className="card">
                <div className="p-8">
                  <h3 className="text-2xl font-display font-semibold text-gray-900 mb-6 flex items-center gap-3">
                    <Star className="w-6 h-6 text-secondary" />
                    Nos coordonnées
                  </h3>
                  
                  <div className="space-y-6">
                    {contactItems.map((item, index) => (
                      <div key={index} className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl hover:bg-primary-50 transition-colors">
                        <div className="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center">
                          {item.icon}
                        </div>
                        <div>
                          <div className="text-sm text-gray-600 font-medium">{item.title}</div>
                          <div className="font-semibold text-gray-900">{item.value}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Call to action luxury */}
              <div className="card-premium bg-gradient-royal p-8 text-white text-center">
                <div className="mb-4">
                  <Award className="w-12 h-12 mx-auto" />
                </div>
                <h3 className="text-2xl font-display font-semibold mb-4">Prêt à commencer ?</h3>
                <p className="mb-6 opacity-90">
                  Contactez-nous dès maintenant pour discuter de vos besoins
                </p>
                <button
                  onClick={scrollToContact}
                  className="btn-gold"
                >
                  Nous contacter
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default HomePage;
